apiVersion: 1
contactPoints:
  - orgId: 1
    name: discord-baraja
    receivers:
      - uid: afrrk56mpquwwf
        type: discord
        settings:
          url: $DISCORD_WEBHOOK_URL
          use_discord_username: false
        disableResolveMessage: false
