name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: write # crear tags y releases
  pull-requests: write # crear/actualizar Release PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
